Repository marcosdosea/RestauranteAki, pull requests merged in 2025-08, with the labels that each got.

#125 Adicionado uma representaçao do diagrama de exceção na seçao Design Model
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, enhancement

#114 Corrigido, removido e ajustado todas as pendencias do Manter Gestor #106 Resolve
  Requisitos/CSU07 - Manter gestor.docx
  Requisitos/prototipos/Tela 11 - Manter Gestor.png
  Requisitos/prototipos/Tela 14 - Adicionar Gestor.png
  Requisitos/prototipos/Tela 15 - Adicionar Garçom.png
Labels: documentation, fix, prototipe

#131 Corrigido diagramas do Design Model
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#127 Corrigido o diagrama de pacotes na seçao Design model(StarUML) seguindo a arquitetura do projeto.
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#129 alterações feitas CSU05 - Manter cardápio.docx #103 Resolve
  Requisitos/CSU05 - Manter cardápio.docx
Labels: documentation, fix

#139 Modelado a arquitetura da aplicação referente ao StarUML, criar e atribuindo responsabilidades ao ViewModel e Mappers.
  Site/RestauranteAki/Core/Core.csproj
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/CardapioProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/ContumProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/GarcomProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/ItemcardapioProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/MesaProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PagamentoProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PedidoItemcardapioProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PedidoProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PersonagemProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PessoaProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/RestauranteProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/CadapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/ContumViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/GarcomViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/ItemcardapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/MesaViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PagamentoViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PedidoItemcardapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PedidoViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PersonagemViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PessoaViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/RestauranteViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
  Site/RestauranteAki/Service/Service.csproj
Labels: enhancement

#141 Adicionado campos e anotações de validação e exibição ([Required] e [Display]) nas propriedades das ViewModels Cardapio, Contum, Garcom, Itemcardapio, Mesa, Pagamento, PedidoItemcardapio, Pedido, Personagem, Pessoa, Restaurante.
  Site/RestauranteAki/RestauranteAkiWeb/Models/CadapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/CardapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/ContumViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/GarcomViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/ItemcardapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/MesaViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PagamentoViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PedidoItemcardapioViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PedidoViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PersonagemViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/PessoaViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/RestauranteViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
Labels: fix

#143 Adicionado o Mappers das classes ViewModel.
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/CardapioProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/ContumProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/GarcomProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/ItemcardapioProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/MesaProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PagamentoProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PedidoItemcardapioProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PedidoProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PersonagemProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/PessoaProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/Mappers/RestauranteProfile.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
Labels: enhancement

#149 Corrigido a implementação das classes de serviço seguinda a arquitetu…
  Site/RestauranteAki/Core/Service/ICardapio.cs
  Site/RestauranteAki/Core/Service/ICardapioService.cs
  Site/RestauranteAki/Core/Service/IContum.cs
  Site/RestauranteAki/Core/Service/IContumService.cs
  Site/RestauranteAki/Core/Service/IGarcom.cs
  Site/RestauranteAki/Core/Service/IGarcomService.cs
  Site/RestauranteAki/Core/Service/IItemcardapio.cs
  Site/RestauranteAki/Core/Service/IItemcardapioService.cs
  Site/RestauranteAki/Core/Service/IMesa.cs
  Site/RestauranteAki/Core/Service/IMesaService.cs
  Site/RestauranteAki/Core/Service/IPagamento.cs
  Site/RestauranteAki/Core/Service/IPagamentoService.cs
  Site/RestauranteAki/Core/Service/IPedido.cs
  Site/RestauranteAki/Core/Service/IPedidoItemcardapio.cs
  Site/RestauranteAki/Core/Service/IPedidoItemcardapioService.cs
  Site/RestauranteAki/Core/Service/IPedidoService.cs
  Site/RestauranteAki/Core/Service/IPersonagem.cs
  Site/RestauranteAki/Core/Service/IPersonagemService.cs
  Site/RestauranteAki/Core/Service/IPessoa.cs
  Site/RestauranteAki/Core/Service/IPessoaService.cs
  Site/RestauranteAki/Core/Service/IRestaurante.cs
  Site/RestauranteAki/Core/Service/IRestauranteService.cs
  Site/RestauranteAki/Service/CardapioService.cs
  Site/RestauranteAki/Service/ContumService.cs
  Site/RestauranteAki/Service/GarcomService.cs
  Site/RestauranteAki/Service/ItemcardapioService.cs
  Site/RestauranteAki/Service/MesaService.cs
  Site/RestauranteAki/Service/PagamentoService.cs
  Site/RestauranteAki/Service/PedidoItemcardapioService.cs
  Site/RestauranteAki/Service/PedidoService.cs
  Site/RestauranteAki/Service/PersonagemService.cs
  Site/RestauranteAki/Service/PessoaService.cs
  Site/RestauranteAki/Service/RestauranteService.cs
Labels: fix

#151 Implementado GarçomService para gerenciar operações do Garçom
  Site/RestauranteAki/Service/GarcomService.cs
Labels: enhancement

#158 Implementei PessoaService para gerenciar operações de Pessoa e configurações do projeto.
  Site/RestauranteAki/RestauranteAkiWeb/Program.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
  Site/RestauranteAki/Service/PessoaService.cs
  Site/RestauranteAki/Service/Service.csproj
Labels: enhancement, fix

#159 Criar projetos de teste. Close #154
  Site/RestauranteAki/RestauranteAki.sln
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/HomeControllerTests.cs
  Site/RestauranteAki/RestauranteAkiWebTests/RestauranteAkiWebTests.csproj
  Site/RestauranteAki/Service/GarcomService.cs
  Site/RestauranteAki/ServiceTests/GarcomServiceTests.cs
  Site/RestauranteAki/ServiceTests/ServiceTests.csproj
Labels: enhancement, fix

#171 Implementado os componentes e layout da view RestauranteAkiWeb #168 Resolve
  Site/RestauranteAki/RestauranteAkiWeb/Views/Home/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Home/Privacy.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/js/site.js
Labels: enhancement

#172 Criado controller referente a Garçom. close #169
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/GarcomController.cs
Labels: enhancement

#180 Implementado PedidoitemcardapioService para gerenciar operações #179 Resolve
  Site/RestauranteAki/Service/PedidoItemcardapioService.cs
Labels: enhancement

#183 Realizado correção em campos do banco de dados e adicinar Aba "Garcom…
  AnaliseProjeto/ModelRestauranteAki.mwb
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
  Site/RestauranteAki/Service/GarcomService.cs
Labels: enhancement, fix

#190 Criado as operações da Controller relacionadas à entidade Itemcardapio dentro da aplicação.
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/ItemcardapioController.cs
Labels: enhancement

#194 Implementar Manter Pedido - Controller + Views
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/PedidoController.cs
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Delete.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Details.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Index.cshtml
Labels: enhancement

#185 Implementada a Controller para Pedido Item Cardapio #181 Resolve
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/PedidoItemcardapioController.cs
Labels: enhancement

#197 Implementado as Views do restaurante e ajustado os icons do layout Close #195
  Site/RestauranteAki/RestauranteAkiWeb/Program.cs
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
  Site/RestauranteAki/Service/RestauranteService.cs
Labels: enhancement

#206 Implementado os testes - Manter pedido. Close #196
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/PedidoControllerTests.cs
  Site/RestauranteAki/RestauranteAkiWebTests/RestauranteAkiWebTests.csproj
  Site/RestauranteAki/ServiceTests/PedidoServiceTests.cs
  Site/RestauranteAki/ServiceTests/ServiceTests.csproj
Labels: enhancement

#201 Implementado CardapioService para gerenciar operações do cardapio.
  Site/RestauranteAki/Service/CardapioService.cs
Labels: enhancement

#187 alterações realizadas na documentação guia e análise de projeto
  Gerenciamento/Guia_Analise_Projeto_RestauranteAki.docx
Labels: documentation, fix

#210 Implementado o teste da Controller do Restaurante #208 Close
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/RestauranteControllerTests.cs
Labels: enhancement

#213 Corrigir validação para campos de manter pedido. Close #211
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
Labels: fix

#216 Implementado Teste para Service e Controller da entidade Cardapio.
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/CardapioController.cs
  Site/RestauranteAki/ServiceTests/CardapioServiceTests.cs
  Site/RestauranteAki/ServiceTests/GarcomServiceTests.cs
Labels: enhancement

#217 Implementado Teste para Service e Controller da entidade Cardapio. cl…
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/CardapioControllerTests.cs
Labels: enhancement

#227 Adicionado views e layout referente ao itemcardapio seguindo o padrão do projeto.
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
  Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
Labels: enhancement

#229 Adicionado views e layout referente a (Garcom e Gestor). Adicionado possibilidade de cadastrar avatar. closes #228
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGarcom.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGestor.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/avatar-default.jpg
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/profile.css
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
Labels: enhancement, fix

#222 Documento guia e análise de projeto adicionado e atualizado
  AnaliseProjeto/Guia_Analise_Projeto_RestauranteAki.docx
Labels: fix

#240 Alterações estruturais de css e padronização de layout. Close #239
  Site/RestauranteAki/RestauranteAkiWeb/Views/Home/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGarcom.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGestor.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/profile.css
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/js/site.js
Labels: UI/UX, fix

#247 Corrigido o design no model.
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#220 Ajustado a RestauranteController e inclusão das Views do Restaurante Close #219
  Site/RestauranteAki/Core/Cardapio.cs
  Site/RestauranteAki/Core/Contum.cs
  Site/RestauranteAki/Core/Itemcardapio.cs
  Site/RestauranteAki/Core/Pessoa.cs
  Site/RestauranteAki/Core/Restaurante.cs
  Site/RestauranteAki/Core/RestauranteAkiContext.cs
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/RestauranteController.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/RestauranteViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
Labels: bug, fix

#254 Criado as operações da Controller relacionadas à entidade Mesa dentro da aplicação.
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/MesaController1.cs
  Site/RestauranteAki/Service/MesaService.cs
Labels: enhancement

#253 Implementado MesaService para gerenciar operações das mesas.
  Site/RestauranteAki/Service/MesaService.cs
Labels: enhancement

#252 Criada as Views para o Restaurante Close #251
  Site/RestauranteAki/Core/Cardapio.cs
  Site/RestauranteAki/Core/Contum.cs
  Site/RestauranteAki/Core/Itemcardapio.cs
  Site/RestauranteAki/Core/Restaurante.cs
  Site/RestauranteAki/Core/RestauranteAkiContext.cs
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/RestauranteController.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/RestauranteViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Delete.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Details.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Edit.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Restaurante/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Shared/_Layout.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
Labels: enhancement, fix

#256 Implementação controller + views da entidade Conta
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/ContaController.cs
  Site/RestauranteAki/RestauranteAkiWeb/Models/ContumViewModel.cs
  Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Delete.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Details.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Edit.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Index.cshtml
Labels: enhancement, UI/UX
