Repository marcosdosea/RestauranteAki, pull requests merged in 2025-09, with the labels that each got.

#266 Erros de compilação nos testes corrigidos
  Site/RestauranteAki/Core/Service/IItemcardapioService.cs
  Site/RestauranteAki/RestauranteAkiWeb/Controllers/ItemcardapioController.cs
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/CardapioControllerTests.cs
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/ItemcardapioControllerTests.cs
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/PessoaControllerTests.cs
  Site/RestauranteAki/RestauranteAkiWebTests/Controllers/RestauranteControllerTests.cs
  Site/RestauranteAki/Service/ItemcardapioService.cs
  Site/RestauranteAki/ServiceTests/ItemcardapioServiceTests.cs
  Site/RestauranteAki/ServiceTests/ServiceTests.csproj
Labels: bug, fix

#267 Resolvidos conflitos de versões + erros estranhos nos projetos de teste
  Site/RestauranteAki/Core/Core.csproj
  Site/RestauranteAki/Core/RestauranteAkiContext.cs
  Site/RestauranteAki/RestauranteAkiWeb/Program.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
  Site/RestauranteAki/Service/Service.csproj
  Site/RestauranteAki/ServiceTests/ContaServiceTests.cs
Labels: bug

#276 Revert "Resolvidos conflitos de versões + erros estranhos nos projetos de teste"
  Site/RestauranteAki/Core/Core.csproj
  Site/RestauranteAki/Core/RestauranteAkiContext.cs
  Site/RestauranteAki/RestauranteAkiWeb/Program.cs
  Site/RestauranteAki/RestauranteAkiWeb/RestauranteAkiWeb.csproj
  Site/RestauranteAki/Service/Service.csproj
  Site/RestauranteAki/ServiceTests/ContaServiceTests.cs
Labels: bug, fix

#268 Revisão básica de css para melhorias de desenvolvimento. Close #262
  Site/RestauranteAki/RestauranteAkiWeb/Views/Conta/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Itemcardapio/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Create.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Details.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Edit.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pedido/Index.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGarcom.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/Views/Pessoa/IndexGestor.cshtml
  Site/RestauranteAki/RestauranteAkiWeb/wwwroot/css/site.css
Labels: fix
