Repository marcosdosea/RestauranteAki, pull requests merged in 2025-06, with the labels that each got.

#20 Corrigido padronização dos botões refente Gestor e ao Garçom closes 18
  Requesitos/prototipos/Tela 11 - Manter Gestor.png
  Requesitos/prototipos/Tela 12 - Manter Garçom.png
Labels: fix

#29 Realizada a correção de campos das telas refente ao Garçom. close #16
  Requesitos/prototipos/Tela 15 - Adicionar Garçom.png
  Requesitos/prototipos/Tela 18 - Detalhes garcom.png
  Requesitos/prototipos/Tela 21 - Deletar garcom.png
  Requesitos/prototipos/Tela 28 - Editar garcom.png
  Requesitos/prototipos/Tela 28 -Editar garcom.png
Labels: documentation, fix

#45 Adicionei associações as entidades no starUML e ao DER:
  Analise de projeto/RestauranteAki.mdj
Labels: documentation, fix

#48 Corrigidos diagramas de colaborações issue 44
  Analise de projeto/RestauranteAki.mdj
Labels: documentation, fix

#50 Adicionei ao Projeto o Banco de Dados no MySQL Workbench
  Analise de projeto/ModelRestauranteAki.mwb
Labels: enhancement
