Repository marcosdosea/RestauranteAki, pull requests merged in 2025-07, with the labels that each got.

#57 Corrigido do nome do package Persistence. Close #55
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#68 Refatorei Atributos do "DER" tabelas Pedido, Personagem, itemPedido, cardapio
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#72 Adicionado fluxo alternativo finalizar pedido e rececber pedido #56 Close
  Requisitos/CSU09 - Receber pedido.docx
  Requisitos/CSU10 - Finalizar pedido.docx
Labels: documentation, fix

#74 Criado os diagramas de Pacotes. Representacao os módulos principais o sistema (Boundary, Control, Entity, Persistence).
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, enhancement

#78 Adicionado os botões que faltava referente ao atendente #73 Close
  Requisitos/prototipos/Tela 30 - Mesa.png
  Requisitos/prototipos/Tela 31 - Pedidos Mesa.png
  Requisitos/prototipos/Tela 32 - Iniciar Pedido.png
  Requisitos/prototipos/Tela 33 - Finalizar Pedido.png
Labels: documentation, fix

#83 Corrigido o Relacionamento e atributos nas entidades Personagem e Pedido. "DER"
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#97 Atualizado modelo DER de acordo com o instruções. close #95
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, fix

#84 Adicionei uma nova Tela "Encerrar conta individual" como fluxo alternativo para o caso de uso "Encerrar conta"
  Requisitos/CSU04 - Encerrar conta.docx
  Requisitos/prototipos/Tela 36  -  Encerrar conta Individual.png
Labels: enhancement, fix

#96 Revisados e corridos os prototipos e adicionado os fluxos dos botões #90 Close
  Requisitos/CSU09 - Receber pedido.docx
  Requisitos/CSU10 - Finalizar pedido.docx
  Requisitos/prototipos/Tela 30 - Mesa.png
  Requisitos/prototipos/Tela 31 - Pedidos Mesa.png
  Requisitos/prototipos/Tela 32 - Iniciar Pedido.png
  Requisitos/prototipos/Tela 33 - Finalizar Pedido.png
Labels: fix

#100 Atualização da Documentação do Banco de Dados
  Gerenciamento/DocumentacaoBanco_RestauranteAki.docx
  Gerenciamento/DocumentaçãoBanco_RestauranteAki.docx
Labels: documentation, fix

#101 Correção descrição de caso de uso 03 - Manter pedido. Close #93
  Requisitos/CSU03 - Manter pedido.docx
Labels: documentation, fix

#117 Foi realizado mapeamento das classes de análise em elementos de projeto (Design Model). E correções necessárias para elaboração do mesmo.
  AnaliseProjeto/RestauranteAki.mdj
Labels: documentation, enhancement, fix
